function m = define_momentarm

m = struct('Tag',{},...
           'Item1',{},...
           'Item2',{},...
           'Visible',{},...
           'Point1',{},...
           'Point2',{},...
           'Length',{});
